### PR TITLE
Emojis.Spoon: Convert JSON to Lua table for faster startup (credits to @octplane)

### PR DESCRIPTION
**Pull request by aldur**
Source on this commit: https://github.com/aldur/dotfiles/commit/8e647c068f08a28829217f517dea07c88eb227e0

### CODE REVIEW

**Comment by cmsj** [comment]
Thanks!

**Comment by ideologysec** [comment]
init.lua:
```
hs.loadSpoon('Emojis')
spoon.Emojis:bindHotkeys({toggle={hyper, 'e'}})
```

Hammerspoon console error:
```
2018-07-13 23:03:51: *** ERROR: /Users/user/.hammerspoon/Spoons/Emojis.spoon/init.lua:62: attempt to index a nil value (field 'code_points')
stack traceback:
	/Users/user/.hammerspoon/Spoons/Emojis.spoon/init.lua:62: in function 'Emojis.init'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:240: in field 'loadSpoon'
	/Users/user/.hammerspoon/init.lua:123: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by ideologysec** [comment]
I do not.

**Comment by aldur** [comment]
How about the logs in Hammerspoon's console after loading the Spoon?

**Comment by aldur** [comment]
OK, let's try to understand what's going on there then.

Could you modify the `init.lua` file as follows, at line 60 (i.e. by adding the `print(emoji)` line?

```lua
            print(emoji)
            local chars =
                hs.fnutils.imap(
                hs.fnutils.split(emoji.code_points.output, "-"),
                function(s)
                    return tonumber(s, 16)
                end
            )
```

**Comment by ideologysec** [comment]
2018-07-18 15:35:40: Starting Emojis Spoon...
2018-07-18 15:35:40: Emojis Spoon: table's not here, generating it from json.
2018-07-18 15:35:40: -- Loading extension: json
2018-07-18 15:35:42: table: 0x604000c70ac0
2018-07-18 15:35:42: *** ERROR: /Users/user/.hammerspoon/Spoons/Emojis.spoon/init.lua:63: attempt to index a nil value (field 'code_points')

**Comment by aldur** [comment]
Right, try with this instead: 

```lua
print(hs.inspect.inspect(emoji))
```

(Sorry, my Lua is a little rusty :))

**Comment by ideologysec** [comment]
2018-07-20 17:27:52: -- Loading Spoon: Emojis
2018-07-20 17:27:52: -- Loading extensions: window.filter
2018-07-20 17:27:52: Starting Emojis Spoon...
2018-07-20 17:27:52: Emojis Spoon: table's not here, generating it from json.
2018-07-20 17:27:52: -- Loading extension: json
2018-07-20 17:27:54: {
  aliases = <1>{},
  aliases_ascii = <table 1>,
  category = "objects",
  code_decimal = "&#127777;",
  emoji_order = "1723",
  keywords = { "object", "science", "health", "hot" },
  name = "thermometer",
  shortname = ":thermometer:",
  unicode = "1f321",
  unicode_alt = "1f321-fe0f"
}
2018-07-20 17:27:54: *** ERROR: /Users/user/.hammerspoon/Spoons/Emojis.spoon/init.lua:63: attempt to index a nil value (field 'code_points')
stack traceback:
	/Users/user/.hammerspoon/Spoons/Emojis.spoon/init.lua:63: in function 'Emojis.init'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:240: in field 'loadSpoon'
	/Users/user/.hammerspoon/init.lua:123: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:596: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by asmagill** [comment]
@aldur, I get the same error when loading the spoon; are you sure that the included `emojis.json` file is up to date with your latest lua code? I don't find a field named "code_points" anywhere in the copy included from my most recent pull from master.

**Comment by aldur** [comment]
Sorry guys, months ago I updated my local Spoon to use a new version of EmojiOne, but then forgot to sync the `emojis` folder in the `master` repository.
Should be fixed with #94.

**Pull request closed without merging**
