### PR TITLE
WinWin: alert on unknown argument

### PR DESCRIPTION
**Pull request by von-forks**
option to moveAndResize()
direction to moveToScreen()

### CODE REVIEW

**Comment by von-forks** [comment]
Hmmm, I just noticed `moveToScreen()` is totally broken. Its argument is `direction` but its using `option` in its code.  Look for another push.

**Comment by cmsj** [comment]
@ashfinal you wrote WinWin initially - any comments on this PR?

**Comment by ashfinal** [comment]
Sorry for the late reply. 

Well, actually moveToScreen() has been fixed in my local code. Adding code to catch unknown argument error is also a good idea.

So, yes, I prefer this PR being merged.

**Comment by cmsj** [comment]
Thanks 👍

**Pull request closed without merging**
