### PR TITLE
New spoon: SpoonUtils

### PR DESCRIPTION
**Pull request by zzamboni**
**Do not merge yet**

@cmsj: A starting point to demonstrate some of the functions described in https://github.com/Hammerspoon/hammerspoon/issues/1376.

These functions could work as a Spoon, but I think they would be better off as part of Hammerspoon, maybe in a new module `hs.spoon` or similar.

### CODE REVIEW

**Comment by zzamboni** [comment]
I've started work on a command-line utility called "spoon" for doing some spoon manipulation, using the SpoonUtils functionality as a backend. Please take a look: https://github.com/zzamboni/spoon

For now only two commands are available "list" and "new". I've been using "new" extensively as I am converting my configuration to Spoon format.

Feedback very welcome.

**Comment by cmsj** [comment]
This is interesting stuff. I think I agree that this would be better in an `hs.spoons` module.

**Comment by zzamboni** [comment]
@cmsj should I put it together as PR on Hammerspoon?

**Comment by zzamboni** [comment]
@cmsj created a PR for an initial version of `hs.spoons`, functionaly identical to this one, for your consideration. I'll be adding more functions and I've also been thinking that `printList()` doesn't really belong there, printing should be done by the user-facing program anyway.

**Comment by zzamboni** [comment]
Closing this in favor of `hs.spoons`.

**Pull request closed without merging**
