### PR TITLE
add Lunette 0.3.1 to Spoons repo

### PR DESCRIPTION
**Pull request by scottwhudson**
Add Lunette to Spoons repository

### CODE REVIEW

**Comment by cmsj** [comment]
I'm happy to merge Lunette, but I think we need to look at some of the docstrings - for our automatic doc generator to work, the docstrings lines need to start with three `-` rather than Lua's normal two.
There also needs to be a little section formatted like lines 1-4 of https://github.com/Hammerspoon/Spoons/blob/master/Source/Caffeine.spoon/init.lua#L1 so we can generate the doc table of contents and page titles properly.

Let me know if I explained that poorly, our docstring stuff is all homegrown and a bit fragile, unfortunately!

**Comment by scottwhudson** [comment]
Howdy @cmsj , sorry this fell off my radar.

I've made the requested docstring changes, lmk if there's anything else I can do!

**Comment by scottwhudson** [comment]
Howdy @cmsj, is there anything else you need from me on this?

**Comment by scottwhudson** [comment]
Howdy @cmsj, is there anything else you need from me on this?

**Comment by cmsj** [comment]
@scottwhudson very sorry, it seems I'm not getting proper notifications for this repo. Do you still want to merge it?

**Pull request closed without merging**
