### PR TITLE
New spoon: FadeLogo

### PR DESCRIPTION
**Pull request by zzamboni**
Show a fading-and-zooming image in the center of the screen.

By default the Hammerspoon logo is shown. Typical use is to show it as an indicator when your configuration finishes loading, by adding the following to the bottom of your `~/.hammerspoon/init.lua` file:
```
   hs.loadSpoon('FadeLogo'):start()
```

Which looks like this (the image, timings, etc. can be customized):
FadeLogo-gif

### CODE REVIEW

**Comment by zzamboni** [comment]
@cmsj @asmagill Graphics is not my strong suit, so I'd very much welcome feedback on how to improve this code. In particular, the zooming sometimes looks a bit "jumpy".

**Comment by asmagill** [comment]
I haven't actually tested it, but it may less cpu intensive to start with the canvas frame at the maximum size you want and then change the image items frame position and size rather then changing the canvas frame... the canvas itself is actually a transparent window with a transparent view and then elements within the view... when you change the canvas frame, all three have to be updated by the OS, whereas just adjusting the image element frame doesn't require the NSWindow or NSView to be adjusted as well.

I'll give it a look this weekend and see if I have any other thoughts.

**Comment by zzamboni** [comment]
@asmagill that was actually my initial attempt (set the canvas with a screen-sized frame, and then adjust only the image size inside it) but I couldn't quite get it to work - that's probably because this is my first time using hs.canvas, so your ideas would be much appreciated :)

**Comment by zzamboni** [comment]
I have been unable to resize the image within the canvas - I must be missing something. Here's aht I have tried so far:

- Calling `spoon.FadeLogo.canvas[1].image:size()` returns the correct image size, but giving it any parameters to set a new size do not result in any changes in the displayed image.
- Reassigning a new (resized) image to `spoon.FadeLogo.canvas[1].image` also does not work.
- Calling `spoon.FadeLogo.canvas:transformation(hs.canvas.matrix.identity():scale(1.1))` scales the image, but crops the resized image to the original size, so the new image is not shown in its entirety.

I must be missing something obvious. Pointers appreciated!

**Comment by zzamboni** [comment]
@asmagill I pushed a fix to resize only the image. For now I'm just reassigning to canvas[1].image. Still, performance is noticeably better, so I had to adjust the timing as well.

It still feels inelegant to have to reassign the image every time - I was thinking maybe I can use `transformation()` with a scale+translate matrix, but haven't figured it out yet.

**Comment by asmagill** [comment]
I would do something like this, which bypasses the need to resize the image itself at all:

~~~lua
local image  = require("hs.image")
local canvas = require("hs.canvas")
local timer  = require("hs.timer")

local size = 500

local hsImage = image.imageFromName(image.systemImageNames.ApplicationIcon)
local hsSize  = 10
local hsInc   = 20

local display = canvas.new{ x = 100, y = 100, h = size, w = size }:show()

display[1] = {
    type         = "image",
    image        = hsImage,
    frame        = {
        x = (size - hsSize) / 2,
        y = (size - hsSize) / 2,
        h = hsSize,
        w = hsSize,
    }
}

local countDown
countDown = timer.doEvery(.2, function()
    hsSize = hsSize + hsInc
    if hsSize <= size then
        display[1].frame = {
            x = (size - hsSize) / 2,
            y = (size - hsSize) / 2,
            h = hsSize,
            w = hsSize,
        }
    else
        countDown:stop()
        display:delete()
        countDown = nil
        display = nil
    end
end)
    
~~~

**Comment by zzamboni** [comment]
@asmagill I have pushed a new update - I used your suggestion to assign the frame of the canvas element. Performance is similar, but I like it better conceptually. I also used your timer code structure, which is cleaner than the one I was using (`doEvery` instead of `doWhile`).

I'm having some confusion about the `hs.geometry` objects - i.e. For some reason I cannot assign a the result from `hs.geometry.scale()` to `canvas[1].frame` directly (which I thought should work).

Still @cmsj I think this is ready for your review/merge when you have a chance.

**Comment by cmsj** [comment]
Merged, thanks!

**Pull request closed without merging**
