### PR TITLE
feat: EmmyLua Spoon

### PR DESCRIPTION
**Pull request by folke**
This Spoon generates EmmyLua annotations for the Hammerspoon docs and for installed Spoons.

## Usage

Simply install the Spoon, use it in your `init.lua` and reload your configuration.

During `init`, any missing or outdated emmy lua annotations will be automatically generated under `{configDir}/annotations`

Your editor needs to have a properly configured [lua-language-server](https://github.com/sumneko/lua-language-server).

If the annotations directory is too much nested under your current directory in your editor, then you may have to add the annotations directory to your workspace to get the completions working:

```json
{
  "Lua.workspace.library": ["/Users/YOUR_USERNAME/.hammerspoon/Spoons/EmmyLua.spoon/annotations"]
}
```

Once the annotations are generated, you may need to restart your editor, so that the lsp server will pickup the annotations.

image

image

Fixes https://github.com/Hammerspoon/hammerspoon/pull/2530

### CODE REVIEW

**Comment by megalithic** [comment]
@folke this is so amazing, thank you!. Love your work!

**Comment by asmagill** [comment]
Still working out how the lua-language-server works with the latest version of BBEdit (14 claims to have added support for it), but I did notice that if I put the command `hs.loadSpoon("EmmyLua")` into my `init.lua` file, it slows down *every* reload, not just when changes to the docs have occurred... does this check the last-modified date on the docs.json file and compare it against the annotations? If not, it probably should... I'm not at a place where I can dig into it now, but you should be able to get at the file dates with `hs.fs`

**Comment by offbyone** [comment]
Could someone consider merging this? It'd be awesome to have in the main repo.

**Comment by muescha** [comment]
> Still working out how the lua-language-server works with the latest version of BBEdit (14 claims to have added support for it), but I did notice that if I put the command `hs.loadSpoon("EmmyLua")` into my `init.lua` file, it slows down _every_ reload, not just when changes to the docs have occurred... does this check the last-modified date on the docs.json file and compare it against the annotations? If not, it probably should... I'm not at a place where I can dig into it now, but you should be able to get at the file dates with `hs.fs`

i added a check in PR #278 `EmmyLua: save timestamps of docs.json to skip if no change`

**Pull request merged**
