### PR TITLE
fix the problem that KSheet only displays in one workspace

### PR DESCRIPTION
**Pull request by Iorest**
This KSheet Spoon can only be displayed in one workspace under multiple spaces. When I call KSheet, I need to return to that workspace.

I found that replacing `self.sheetView:level(hs.drawing.windowLevels.modalPanel)` with`self.sheetView:level(hs.drawing.windowLevels.tornOffMenu)` fix this problem.

### CODE REVIEW

**Comment by cmsj** [comment]
@ashfinal any thoughts on this?

**Comment by cmsj** [comment]
Thanks for this, and apologies for the slow response. I've merged it in by hand to undo the change you made to the zip file - there's no need to rebuild those, it happens automatically when new code is pushed :)

**Comment by cncsl** [comment]
hello, gays. I'm new to hammerspoon and KSheet. 

I’ve noticed that when the screen configuration changes (e.g., when connecting or disconnecting an external monitor), the cheat sheet can render incorrectly. This seems to be because the sheetView properties are calculated during initialization(`function obj:init()`) and are not recalculated afterward.

I believe this behavior was introduced by this PR. What was the reasoning behind moving this calculation from `show()` to `init()`?

image

**Comment by cncsl** [comment]
Is there free, possible and safe to patch like below ?
image

**Pull request merged**
