### PR TITLE
Add center, undo, larger & smaller operations to WindowHalfsAndThirds spoon

### PR DESCRIPTION
**Pull request by matthewfallshaw**
Some extensions to WindowHalfsAndThirds spoon.

- center: centers the window without resizing it
- undo: move operations store the previous window state - undo will restore the active window
- larger & smaller: operations to grow or shrink the window

I've also boldly refactored in ways that made the code seem to me to be clearer and easier to modify.

For some reason HS auto generates a blank docs.json every time it loads this spoon. I used the newly added obj.generate_docs_json to generate them, but I'd love someone else to work out why the normal automatic mechanism is broken.

### CODE REVIEW

**Comment by cmsj** [comment]
Paging Dr @zzamboni who wrote that Spoon :)

**Comment by zzamboni** [comment]
Looks good to me, and adds some nice new functionality. Thanks @matthewfallshaw!

@cmsj can you generate the docs on your side? Otherwise I can create a fork and generate them myself, but it seems like overkill.

@matthewfallshaw this is the script I use for updating the `docs.json` file within the spoon, I run it within the spoon's directory:
```
#!/bin/bash
hs -c "hs.doc.builder.genJSON(\"$(pwd)\")" | grep -v "^--" > docs.json
```

**Comment by zzamboni** [comment]
@matthewfallshaw I just noticed some nice new features, such as the `half*` functions cycling through 50%, 40%, 60%, and the `third*` wrapping over to the other side of the screen - very nice!

I'd been unhappy with the quality of this code since I wrote it (too much repetition), but never took the time to improve it - I'm very happy that you found it useful enough to improve it :)

**Comment by matthewfallshaw** [comment]
Thank you, @zzamboni. I have very much enjoyed using and working with this and several of your other Spoons.

What's the next step in merging these changes? @cmsj to generate the docs? Is there anything I can do?

**Comment by zzamboni** [comment]
Hi @matthewfallshaw thanks for the nice words.

The next step is usually just waiting for @cmsj to have some time to merge the changes :)

**Comment by cmsj** [comment]
Thanks guys!

**Pull request closed without merging**
