### PR TITLE
WinWin - Fix "fullscreen". Add Maximize/Minimize options

### PR DESCRIPTION
**Pull request by jacobisaliveandwell**
This PR seeks to make "fullscreen" consistent with other notions of "fullscreen", and add maximize/minimize options instead.

I do expect my "fullscreen" change to be contentious, but given the chosen name and behavior, I'm not sure how to get around that and be "backwards compatible".

### CODE REVIEW

**Comment by lanox** [comment]
How do you exit the full screen once you are in it ?

**Comment by cmsj** [comment]
Let's see if @ashfinal has an opinion, as the author of WinWin :)

**Comment by jacobisaliveandwell** [comment]
@lanox Fair question. The way I see the plugin in it's current state, it's not trying to do anything more than be declarative, with very little logic. That said, if @ashfinal would like to weigh in, I'm just as happy making `"fullscreen"` use `hs.window.toggleFullScreen`.

**Comment by lanox** [comment]
> @lanox Take a look at this last commit. It's a big change, but I think addresses your point, which has been bugging me too.

Thanks, I will give it a try.

**Comment by jacobisaliveandwell** [comment]
@ashfinal ping

**Comment by cmsj** [comment]
Since it's really just adding functionality, I decided to go ahead with the merge. Thanks!

**Pull request closed without merging**
