### PR TITLE
Seal Spoon : Avoid search by space (" ") & user_actions: Accept choice subText

### PR DESCRIPTION
**Pull request by joaocsilva**
### When searching by space (meaning " ") an error is thrown:
```
ERROR: LuaSkin: hs.chooser:choices error - .hammerspoon/Spoons/Seal.spoon/init.lua:303: attempt to index a nil value (global 'cmd')
stack traceback:
  .hammerspoon/Spoons/Seal.spoon/init.lua:303: in function 'Seal.choicesCallback'
  [C]: in method 'refreshChoicesCallback'
  .hammerspoon/Spoons/Seal.spoon/init.lua:344: in function <.hammerspoon/Spoons/Seal.spoon/init.lua:344>
```

### Plugin user_actions: Accept a `description` key to be used as `subText` of the choice.
http://www.hammerspoon.org/docs/hs.chooser.html#choices

**NOTE:**
I am not sure about the `.zip` file, the one that I pushed is basically a zip of the folder `Source/Seal.spoon/`.

### CODE REVIEW

**Comment by cmsj** [comment]
Are the url encoding and favicon changes intended to be included in this?

(I am always grateful for contributions from Hammerspoon users, but in general it's a lot easier for me to get through PR reviews if they are focused on a single thing, and describe all of the changes included)

**Comment by cmsj** [comment]
I've pulled out the Seal whitespace fix into #224 until we figure out what of the rest of this should be merged.

**Comment by joaocsilva** [comment]
Hi @cmsj , thank you for having a look into this.
You are right, I'll move those changes into a new pull request with a proper description.

**Comment by joaocsilva** [comment]
@cmsj I am closing this PR is favour of #231 since the query fix was already applied.

**Pull request closed without merging**
