### PR TITLE
New spoon: WindowHalfsAndThirds

### PR DESCRIPTION
**Pull request by zzamboni**
Move and resize windows.

### CODE REVIEW

**Comment by cmsj** [comment]
As I mentioned on IRC, I think the name is much too generic. It's likely we're going to end up with a bunch of opinionated window management spoons, so their names ought to say something about their core philosophy IMO :)

**Comment by zzamboni** [comment]
Agree - do you have any suggestions? "WindowMovement", "WindowManagement" also seem very generic. Another idea would be to introduce namespacing (maybe based on github names) so that you could have "zzamboni/WindowManagement", for example.

**Comment by zzamboni** [comment]
@cmsj I have taken out the screen-movement functionality (will put in a separate spoon) and renamed this one to "WindowHalfsAndThirds", which I think reflects its focus. Didn't rename the branch to keep things easy.

**Comment by zzamboni** [comment]
Closed in favor of https://github.com/Hammerspoon/Spoons/pull/37 (renamed branch to make things consistent)

**Pull request closed without merging**
