### PR TITLE
Truncate preview of large clipboard texts

### PR DESCRIPTION
**Pull request by sharat87**
This will show a small preview of large clipboard texts, but the full content is available for searching and pasting.

### CODE REVIEW

**Comment by cmsj** [comment]
I wonder if it would be a good idea to have the truncation length be exposed as a variable users can configure?

**Comment by sharat87** [comment]
@cmsj, personally, that feels like _too much configuration_, but since it's more like a one-line change, I'm not going to make my case strongly. 🙂

Shall I add a variable for it then?

**Comment by cmsj** [comment]
Yes please 😁

**Comment by sharat87** [comment]
Done.

**Comment by cmsj** [comment]
Thanks!

**Pull request merged**
