### PR TITLE
Add Binder

### PR DESCRIPTION
**Pull request by casouri**
This spoon gives you the power to bind sequential keys.

The main function is `recursiveBind`. 

As an example:

```
      mymapWithName = {
         [singleKey('h', 'Commander')] = spoon.Commander.show,
         [singleKey('`', 'run command')] = runCommand,
         [singleKey('f', 'find+')] = {
            [singleKey('D', 'Desktop')] = function() openWithFinder('~/Desktop') end,
            [singleKey('p', 'Project')] = function() openWithFinder('~/p') end,
            [singleKey('d', 'Download')] = function() openWithFinder('~/Downloads') end,
            [singleKey('a', 'Application')] = function() openWithFinder('~/Applications') end,
            [singleKey('h', 'home')] = function() openWithFinder('~') end,
            [singleKey('f', 'hello')] = function() hs.alert.show('hello!') end},
         [singleKey('t', 'toggle+')] = {
            [singleKey('v', 'file visible')] = function() hs.eventtap.keyStroke({'cmd', 'shift'}, '.') end
         },
         [singleKey('o', 'open+')] = {
            [singleKey('e', 'Emacs')] = function() hs.application.launchOrFocus('Emacs') end,
            [singleKey('s', 'Safari')] = function() hs.application.launchOrFocus('Safari') end,
            [singleKey('f', 'Finder')] = function() hs.application.launchOrFocus('Finder') end,
            [singleKey('d', 'Dictionary')] = function() hs.application.launchOrFocus('Dictionary') end,
            [singleKey('m', 'Mail')] = function() hs.application.launchOrFocus('Mail') end,
            [singleKey('q', 'QQ')] = function() hs.application.launchOrFocus('QQ') end,
            [singleKey('w', 'Wechat')] = function() hs.application.launchOrFocus('Wechat') end,
            [singleKey('g', 'Google')] = function() os.execute('open http://google.com') end,
         },
         [singleKey('i', 'insert+')] = {
            [singleKey('e', 'emoji')] = insertEmoji,
         }
      }

      hs.hotkey.bind(hyperMod, 'space', spoon.Binder.recursiveBind(mymapWithName))

```

So I first create a keymap, you can see `h` will invoke `spoon.Commander.show`; `f`, on the other hand, will invoke another layer of keymaps, so `f D` will invoke `function() openWithFinder('~/Desktop') end`.

`singleKey` returns a table of `{{}, 'key', 'description'}`

Then I pass this keymap to `recursiveBind`, which return an entry function of the sequential keybindings. And I bind `hyper+space` to it.

Now if I press `hyper+space h` I invoke `spoon.Commander.show`.

**Visual demonstration:**

- press `hyper+space`:

screen shot 2018-04-10 at 9 33 16 pm

- press `f`:
screen shot 2018-04-10 at 9 33 20 pm

### CODE REVIEW

**Comment by cmsj** [comment]
This is a great idea, the only slight quibble I have is the name - "Binder" is quite generic, but I can't immediately think of a better solution. If we can't come up with anything I'll merge this, but I prefer it when the name of a spoon draws attention to its main benefit, which in this case I think is the recursive binding and the little hint bar along the bottom.

Any thoughts?

**Comment by casouri** [comment]
Maybe `recusiveBind`, which is the name of the major function?

**Comment by casouri** [comment]
Yeah do you like it?

**Comment by cmsj** [comment]
Yes :)

**Comment by casouri** [comment]
Wait don't merge yet.

**Comment by cmsj** [comment]
Thanks!

**Pull request closed without merging**
