### PR TITLE
Implemented customization of the size of the cheatsheet and order of …

### PR DESCRIPTION
**Pull request by dmgerman**
I find ModalMgr to be an amazing spoon. but it has some usability problems:

1. The window is too wide. I frequently have to rotate my head to be able to read all the options
2. The ordering makes it difficult to find items. One has to go left-right-left-right to read the options
3. the size of the window is hardcoded. it is too wide, this means my eyes have to move to read the options.

I have added customization. Basically these variables:

```
-- customize width and height of Cheatsheet
obj.width_factor = 0.30
obj.height_factor = 0.30
-- minimum sizes
obj.min_width = 200
obj.min_height = 200

-- alighment for right column
obj.alignmentRightColumn = 'right'
obj.fillByRow = false
```

- The "factor" is the width of the window with respect to the current screen.
- the "min" is the minimum size of the window to use
- the alignment for the right column. Allows to change it
- whether to fill the window by Row or by column. if true it will fill rows first. if false, it will fill columns first. I think by column is easier to read.

One extra advantage of these changes is that each ModalMgr window can have different sizes or filling strategies.

### CODE REVIEW

**Comment by cmsj** [comment]
ping @ashfinal as author of ModalMgr

**Comment by dmgerman** [comment]
I am sorry, I don't know if there is anything I should do to have the checks passed.

**Comment by cmsj** [comment]
> I am sorry, I don't know if there is anything I should do to have the checks passed.

Annoyingly GitHub makes it extremely difficult to run checks when third parties submit PRs and still be able to report useful results. Please ignore the failing checks.

**Comment by dmgerman** [comment]
I have rebased the pull request. Is there anything else that I should do?

**Pull request merged**
