### PR TITLE
New Spoon: TextClipboardHistory

### PR DESCRIPTION
**Pull request by zzamboni**
Maintain a history of clipboard items.

### CODE REVIEW

**Comment by asmagill** [comment]
While @cmsj is more active in the Spoon arena then I am, I would be more comfortable making this official if support was added to keep private or transient pasteboard data from being recorded at all as described at http://nspasteboard.org.  You can iterate through `hs.pasteboard.pasteboardTypes` to see if any of the specified identifiers are present and if so, ignore the item (although the code is a little ugly, you can see one example of this at https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua, specifically around lines 65 and 109)

**Comment by zzamboni** [comment]
@asmagill thanks for the comment and the pointer! I have shamelessly reused your code - please let me know if this is OK.

Your clipper also has some interesting ideas I like - such as deduplication. I may reuse some of those as well :)

**Comment by asmagill** [comment]
I have no objections at all -- reuse away!  If you look at the comments at the top, you'll see that I had some other ideas on things to add, but kind of lost steam once my basic needs at the time were met.

I look forward to seeing where you decide to go with it!

**Comment by cmsj** [comment]
Thanks, merged. (for bonus future points, it'd be fun to have multiple datatypes supported, and persisting the history to disk somehow :D )

**Comment by zzamboni** [comment]
@cmsj Thanks for merging! The history is already persisted using `hs.settings`. I'd love to add multiple datatypes, I had images semi-working at some time but will take a look again when I have some time :)

**Pull request closed without merging**
